spring:
  application:
    name: transport-management
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:classpath:.env
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

logging:
  level:
    root: INFO

server:
  http2:
    enabled: true
  compression:
    enabled: true

twilio:
  account-sid: ${TWILIO_SID}
  auth-token: ${TWILIO_TOKEN}
  phone-number: ${TWILIO_NUMBER}


